language: go
go:
  - stable
cache: yarn
services:
  - docker
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - make
  - goveralls -service=travis-ci -ignore="internal/handlers/static.go,internal/handlers/tmpls/tmpls.go"
  - make buildDockerImage
  - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "master" ]]; then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push acacio/& docker push acacio/url_shortener:arm; fi'
deploy:

env:
  global:
    secure: n+8G1Y52ijOL9xLJm/dO80F3VipkqovhMlE6NOkYBAjGLAzbvWuU1Qh/fCmMc/m2yNk5S/2jH3bIG/w/npLBjegqfIvBJhRvyGFUDdH1LiJ9P+oO+NYtNCQCLW8hIRs+tUi8XdOtxLVBP8h90RGKsP0zgycd+UX221u2CpBn2ogWDOwV9lo2Y/UQ0n8CTdRrVMtnx3XhHbL220PII6QTd/5wmP314HPbbp+9ihNCoyCLkHjSo+ZJ25NMO7rVsci91rfg6GJclWV6yd1LBMA5ofReJZkalZt6PK+yEO0+OIL7MaXscRe74EZxy7HJrKsSTTo57xttEmECNSlf/AM6LMqXRi8ble8ScEqhIW7H/FtXGiyTwueYSAsIKmNGnkx9eCxo/rsF/F3serLzffSzbdxFe1OyeAxZnsbhazA1Z+JnnjdhtieZ2mjeIZeDXfSTNF23Ul5wiS+eaopSWe0r+XdWUe/MrMUvyRFy9T6U4MmTWjiA7xf8HMUWScN981MgPrkmd3rfv/UnCt8xJ353UTCHqugQ+Y58SmGIN3CVLS/hGg8AGl/FSjbEEShZ5qS1bbNLI0++l0W2zDFRNtHsJw1E/byfUEFyfNpVzf/z3PYUm0YkK/mx5pIYDQSI2zLlggqsfy5yQQrdbgqzbk3ys2+8TM37BQxUjP6QLcVVUSk=
